spring.application.name=posts-service
#config server config
spring.config.import=configserver:http://localhost:8888

#spring ai
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.max-tokens=500

