input {
  file {
    type => "log"
    path => "D:/WorkPlace/LinkedinProject/logs/*/application-*.log"
    start_position => "beginning"
    sincedb_path => "NUL"
  }
}
filter {
  # Add filters as needed
}

output {
  stdout{
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "linkedIn_logs-%{+YYYY.MM.dd}"
  }
}